#!/usr/bin/env python3
"""Build a single-file context bundle for handing to an LLM chatbot.

Concatenates the template's canonical orientation files into one Markdown
file so a non-technical user can upload/paste one document instead of
several, at the start of a chatbot session. See README.md's
"LLM chatbot 工作方式" section for how it's used.

Usage:
    python scripts/build_context_bundle.py [--output PATH]

Stdlib only — no install step required.
"""

from __future__ import annotations

import argparse
import hashlib
import subprocess
import sys
from datetime import datetime
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent

# Canonical orientation files an LLM chatbot needs before it can safely
# reason about this project. Deliberately excludes task-specific files
# (a `shared/` contract, code, data) — those get attached separately, only
# when the task actually needs them. Keep in rough reading order: rules,
# boundary, index, product intent, architecture.
BUNDLE_FILES = [
    "AGENTS.md",
    "docs/TEMPLATE_BOUNDARY.md",
    "docs/FILE_MANIFEST.md",
    "ai/PROJECT_CONTEXT.md",
    "ai/ARCHITECTURE_RULES.md",
    "ai/DESIGN_RULES.md",
]

# One line per bundled file, telling the reader what it's for without having
# to infer it from the content alone.
BUNDLE_FILE_PURPOSES = {
    "AGENTS.md": "Rules to follow when helping change this project.",
    "docs/TEMPLATE_BOUNDARY.md": "Which files are the template's own rules (do not rewrite them as a side effect of a feature request) vs. this project's own content (safe to change).",
    "docs/FILE_MANIFEST.md": "Index of every file in the project and what it's for.",
    "ai/PROJECT_CONTEXT.md": "What this specific tool is for, who it's for, and what \"done\" means.",
    "ai/ARCHITECTURE_RULES.md": "Code structure rules — what's allowed to depend on what.",
    "ai/DESIGN_RULES.md": "Default frontend visual rules — typography, color/contrast, spacing, tables, media fit.",
}

# SHA-256 of a file's content exactly as the template ships it, unedited.
# Used to warn the reader when a file that's supposed to be filled in with
# this project's own specifics still has the generic placeholder content —
# so the reader doesn't mistake template boilerplate for confirmed facts.
KNOWN_DEFAULT_HASHES = {
    "ai/PROJECT_CONTEXT.md": "88c0a0336a066d499771660180f4ad6fc66008d0b3a442bcb433dd5b5aeac152",
}

DEFAULT_OUTPUT = PROJECT_ROOT / "LLM_CONTEXT_BUNDLE.md"

PREAMBLE = """# LLM Context Bundle

Generated: {timestamp}
Source commit: {commit}
Generated by `scripts/build_context_bundle.py` — do not hand-edit this file; edit the source files listed below and regenerate.

This bundle contains the template's canonical orientation files, not the whole project. If this task needs a specific `shared/` contract, data file, or code file, ask the user for it separately.

Included files:
{file_list}
{default_content_warning}"""


def get_source_commit() -> str:
    try:
        result = subprocess.run(
            ["git", "rev-parse", "--short", "HEAD"],
            cwd=PROJECT_ROOT,
            capture_output=True,
            text=True,
            timeout=5,
            check=True,
        )
    except (OSError, subprocess.SubprocessError):
        return "unknown (git not available)"
    commit = result.stdout.strip()
    if not commit:
        return "unknown"
    dirty = subprocess.run(
        ["git", "status", "--porcelain"],
        cwd=PROJECT_ROOT,
        capture_output=True,
        text=True,
        timeout=5,
    )
    if dirty.returncode == 0 and dirty.stdout.strip():
        return f"{commit} (plus uncommitted changes)"
    return commit


def is_unedited_default(path: str, content: str) -> bool:
    expected = KNOWN_DEFAULT_HASHES.get(path)
    if expected is None:
        return False
    return hashlib.sha256(content.encode("utf-8")).hexdigest() == expected


def build_bundle() -> str:
    missing = [path for path in BUNDLE_FILES if not (PROJECT_ROOT / path).is_file()]
    if missing:
        raise FileNotFoundError(
            "missing canonical source file(s), refusing to produce a partial bundle: "
            + ", ".join(missing)
        )

    contents = {path: (PROJECT_ROOT / path).read_text(encoding="utf-8") for path in BUNDLE_FILES}
    still_default = [path for path in BUNDLE_FILES if is_unedited_default(path, contents[path])]

    file_list = "\n".join(
        f"- `{path}` — {BUNDLE_FILE_PURPOSES.get(path, '(no description)')}" for path in BUNDLE_FILES
    )
    if still_default:
        warning_lines = "\n".join(f"- `{path}`" for path in still_default)
        default_content_warning = (
            "\nWarning — still template placeholder content, not yet customized for this project. "
            "Treat its specifics as provisional, not confirmed facts, until the user says otherwise:\n"
            f"{warning_lines}\n"
        )
    else:
        default_content_warning = ""

    sections = [
        PREAMBLE.format(
            timestamp=datetime.now().isoformat(timespec="seconds"),
            commit=get_source_commit(),
            file_list=file_list,
            default_content_warning=default_content_warning,
        )
    ]
    for path in BUNDLE_FILES:
        sections.append(f"---\n## FILE: {path}\n---\n\n{contents[path].rstrip()}\n")

    return "\n".join(sections)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args(argv)

    try:
        bundle = build_bundle()
    except FileNotFoundError as exc:
        print(f"error: {exc}")
        return 1

    args.output.write_text(bundle, encoding="utf-8")
    size_kb = args.output.stat().st_size / 1024
    try:
        display_path = args.output.resolve().relative_to(PROJECT_ROOT)
    except ValueError:
        display_path = args.output
    print(f"Wrote {display_path} ({size_kb:.1f} KB)")
    print("Upload or paste this single file to your chatbot at the start of a session.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
