#!/usr/bin/env python3
"""Build a single-file context bundle for handing to an LLM chatbot.

Concatenates every file docs/FILE_MANIFEST.md's "Always-present foundation"
table marks `Core` in its Bundle column into one Markdown file, so a
non-technical user can upload/paste one document instead of several, at the
start of a chatbot session. See README.md's "LLM chatbot 工作方式" section
for how it's used, and docs/FILE_MANIFEST.md for how to add or remove a
file from the bundle — this script has no file list of its own.

Usage:
    python scripts/build_context_bundle.py [--output PATH]

Stdlib only — no install step required.
"""

from __future__ import annotations

import argparse
import hashlib
import subprocess
import sys
from datetime import datetime
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent

FILE_MANIFEST_PATH = PROJECT_ROOT / "docs" / "FILE_MANIFEST.md"
MANIFEST_TABLE_HEADING = "## Always-present foundation"
MANIFEST_EXPECTED_HEADER = ["Path", "Canonical / Instance", "Bundle", "Why it exists", "Read or update when"]


def parse_bundle_manifest() -> list[tuple[str, str]]:
    """Return (path, purpose) pairs for every file marked ``Core`` in the
    Bundle column of docs/FILE_MANIFEST.md's "Always-present foundation"
    table, in table order.

    That table is the single source of truth for what ships in
    LLM_CONTEXT_BUNDLE.md — see ADR-005 and ADR-007 in docs/DECISIONS.md.
    This script deliberately keeps no separate file list of its own, so a
    file can never be canonical-but-forgotten by the bundle: every row must
    say ``Core`` or ``—`` explicitly, or this function refuses to guess.
    """
    if not FILE_MANIFEST_PATH.is_file():
        raise ValueError(f"missing {FILE_MANIFEST_PATH.relative_to(PROJECT_ROOT)}")

    text = FILE_MANIFEST_PATH.read_text(encoding="utf-8")
    if MANIFEST_TABLE_HEADING not in text:
        raise ValueError(
            f"{FILE_MANIFEST_PATH.name} is missing the '{MANIFEST_TABLE_HEADING}' section "
            "that scripts/build_context_bundle.py parses for the bundle file list."
        )
    section = text.split(MANIFEST_TABLE_HEADING, 1)[1].split("\n## ", 1)[0]
    table_rows = [line for line in section.splitlines() if line.strip().startswith("|")]
    if len(table_rows) < 2:
        raise ValueError(
            f"could not find a table under '{MANIFEST_TABLE_HEADING}' in {FILE_MANIFEST_PATH.name}"
        )

    def split_row(row: str) -> list[str]:
        return [cell.strip() for cell in row.strip().strip("|").split("|")]

    header = split_row(table_rows[0])
    if header != MANIFEST_EXPECTED_HEADER:
        raise ValueError(
            f"{FILE_MANIFEST_PATH.name}'s table header changed shape — expected "
            f"{MANIFEST_EXPECTED_HEADER}, got {header}. Update "
            "parse_bundle_manifest() in scripts/build_context_bundle.py to match."
        )

    core_files: list[tuple[str, str]] = []
    for row in table_rows[2:]:  # skip header row and the "| --- |" separator
        cells = split_row(row)
        if len(cells) != len(MANIFEST_EXPECTED_HEADER):
            raise ValueError(f"malformed row in {FILE_MANIFEST_PATH.name}'s table: {row!r}")
        path_cell, _canonical_instance, bundle_cell, why_cell, _when_cell = cells
        path = path_cell.strip("`")
        if bundle_cell not in ("Core", "—"):
            raise ValueError(
                f"{FILE_MANIFEST_PATH.name} row for `{path}` has an unrecognized Bundle "
                f"value {bundle_cell!r} (must be 'Core' or '—'). Every row must make this "
                "call explicitly — see ADR-005 in docs/DECISIONS.md."
            )
        if bundle_cell == "Core":
            core_files.append((path, why_cell))
    return core_files


# SHA-256 of a file's content exactly as the template ships it, unedited.
# Used to warn the reader when a file that's supposed to be filled in with
# this project's own specifics still has the generic placeholder content —
# so the reader doesn't mistake template boilerplate for confirmed facts.
KNOWN_DEFAULT_HASHES = {
    "ai/PROJECT_CONTEXT.md": "88c0a0336a066d499771660180f4ad6fc66008d0b3a442bcb433dd5b5aeac152",
}

DEFAULT_OUTPUT = PROJECT_ROOT / "LLM_CONTEXT_BUNDLE.md"

PREAMBLE = """# LLM Context Bundle

Generated: {timestamp}
Source commit: {commit}
Generated by `scripts/build_context_bundle.py` — do not hand-edit this file; edit the source files listed below and regenerate.

This bundle contains the template's canonical orientation files, not the whole project. If this task needs a specific `shared/` contract, data file, or code file, ask the user for it separately.

Included files:
{file_list}
{default_content_warning}"""


def get_source_commit() -> str:
    try:
        result = subprocess.run(
            ["git", "rev-parse", "--short", "HEAD"],
            cwd=PROJECT_ROOT,
            capture_output=True,
            text=True,
            timeout=5,
            check=True,
        )
    except (OSError, subprocess.SubprocessError):
        return "unknown (git not available)"
    commit = result.stdout.strip()
    if not commit:
        return "unknown"
    dirty = subprocess.run(
        ["git", "status", "--porcelain"],
        cwd=PROJECT_ROOT,
        capture_output=True,
        text=True,
        timeout=5,
    )
    if dirty.returncode == 0 and dirty.stdout.strip():
        return f"{commit} (plus uncommitted changes)"
    return commit


def is_unedited_default(path: str, content: str) -> bool:
    expected = KNOWN_DEFAULT_HASHES.get(path)
    if expected is None:
        return False
    return hashlib.sha256(content.encode("utf-8")).hexdigest() == expected


def build_bundle() -> str:
    bundle_files = parse_bundle_manifest()
    paths = [path for path, _purpose in bundle_files]

    missing = [path for path in paths if not (PROJECT_ROOT / path).is_file()]
    if missing:
        raise FileNotFoundError(
            "docs/FILE_MANIFEST.md marks these files Core but they don't exist, "
            "refusing to produce a partial bundle: " + ", ".join(missing)
        )

    contents = {path: (PROJECT_ROOT / path).read_text(encoding="utf-8") for path in paths}
    still_default = [path for path in paths if is_unedited_default(path, contents[path])]

    file_list = "\n".join(f"- `{path}` — {purpose}" for path, purpose in bundle_files)
    if still_default:
        warning_lines = "\n".join(f"- `{path}`" for path in still_default)
        default_content_warning = (
            "\nWarning — still template placeholder content, not yet customized for this project. "
            "Treat its specifics as provisional, not confirmed facts, until the user says otherwise:\n"
            f"{warning_lines}\n"
        )
    else:
        default_content_warning = ""

    sections = [
        PREAMBLE.format(
            timestamp=datetime.now().isoformat(timespec="seconds"),
            commit=get_source_commit(),
            file_list=file_list,
            default_content_warning=default_content_warning,
        )
    ]
    for path in paths:
        sections.append(f"---\n## FILE: {path}\n---\n\n{contents[path].rstrip()}\n")

    return "\n".join(sections)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args(argv)

    try:
        bundle = build_bundle()
    except (FileNotFoundError, ValueError) as exc:
        print(f"error: {exc}")
        return 1

    args.output.write_text(bundle, encoding="utf-8")
    size_kb = args.output.stat().st_size / 1024
    try:
        display_path = args.output.resolve().relative_to(PROJECT_ROOT)
    except ValueError:
        display_path = args.output
    print(f"Wrote {display_path} ({size_kb:.1f} KB)")
    print("Upload or paste this single file to your chatbot at the start of a session.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
